export const FETCH_COUNTRIES = 'POST/FETCH_COUNTRIES';
export const SET_SELECT_COUNTRY_ID = 'SET_SELECT_COUNTRY_ID';
export const FETCH_CATEGORIES = 'POST/FETCH_CATEGORIES';
export const FETCH_APPS_DATA = 'POST/FETCH_APPS_DATA';
